version: 2
updates:
  - package-ecosystem: "npm"
    directory: "."
    schedule:
      interval: "daily"
    target-branch: "v3"
  - package-ecosystem: "github-actions"
    directory: ".github/"
    schedule:
      interval: "daily"
    target-branch: "v3"
